Algoritmo "Exemplo3"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Digitando-se dois numeros inteiros e exiba a soma
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/02/2026
Var
// Seção de Declarações das variáveis 
num1, num2, soma:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
              escreva("Digite o primeiro numero: ")
              leia(num1)
               escreva("Digite o segundo numero: ")
              leia(num2)
              soma<-num1+num2
              escreva("O resultado é: ",soma)
Fimalgoritmo