Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/02/2026
Var
// Seção de Declarações das variáveis 
idade:inteiro
nome:caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
                idade<-18
                nome<-"Carlos"
                escreva("Seu nome é ", nome," e tem ", idade," anos de idade")
         

Fimalgoritmo